### PR TITLE
auto scale down mesos slave

### PR DESCRIPTION
**Pull request by loky9000**
please update tag 1.0-42p

### CODE REVIEW

**Comment by loky9000** [comment]
retest this please

**Comment by loky9000** [comment]
retest this please

**Comment by loky9000** [comment]
retest this please

**Comment by DmZ** [comment]
retest this please

**Comment by DmZ** [comment]
retest this please

**Comment by loky9000** [comment]
retest this please

**Comment by loky9000** [comment]
retest this please

**Comment by loky9000** [comment]
retest this please

**Comment by loky9000** [comment]
retest this please

**Comment by loky9000** [comment]
retest this please

**Comment by loky9000** [comment]
retest this please

**Pull request merged**
